version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
  - dependency-name: Xamarin.Google.Android.Material
    versions:
    - 1.2.1.1
    - 1.3.0
  - dependency-name: Xamarin.AndroidX.DrawerLayout
    versions:
    - 1.1.1.1
  - dependency-name: Xamarin.AndroidX.CoordinatorLayout
    versions:
    - 1.1.0.6
  - dependency-name: Xamarin.AndroidX.CardView
    versions:
    - 1.0.0.6
  - dependency-name: Xamarin.AndroidX.AppCompat.AppCompatResources
    versions:
    - 1.2.0.6
